### PR TITLE
add options to set response format as xml or geojson

### PR DESCRIPTION
**Pull request by cohenlea**

### CODE REVIEW

**Comment by moberwasserlechner** [comment]
@cohenlea Could you please add tests for the formats `geojson` and `xml` testing the response. 

You only test the building of the request. JOpencage needs a specific json format to map to the Java Object if sth else is returned the lib most probably gives you an exception.

For XML we could use an extension: https://github.com/FasterXML/jackson-dataformat-xml but for geojson I have no immediate solution.

**Comment by cohenlea** [comment]
thanks @moberwasserlechner I will add some tests and see if I run into that issue

**Comment by cohenlea** [comment]
Hi @moberwasserlechner I added some tests and it's fine getting the response with geojson (because it's really just json), but to read it I would probably need to create new Response and Result objects for a geojson response because the structure is slightly different ("features" instead of "results" and geometry.coordinates[] instead of geometry.lat and geometry.lng). What do you think?

You're right that it breaks trying to get the response with xml, but the response structure appears to be the same as with json so if we use the FasterXML extension, we could still use the original response/result objects.

**Comment by freyfogle** [comment]
Hi everyone, thanks for your efforts. Totally up to you, but just to add some context, 95+% of requests to the OpenCage API are for the JSON format. I suppose I could look in more detail, maybe Java users are more likely to request XML, but I don't think it is critical. As long as JSON works well that is probably fine.

**Comment by moberwasserlechner** [comment]
@freyfogle thanks for the insights. 

I don't think Java users are more likely to use XML. A JSON response from REST API is expected by everyone. So I would not support XML in this lib because the usage numbers are that low. Another thing is the addional dependency although that could be resolved by using JAXB.

@cohenlea Do you had a specific use case in mind when wanting to support XML?

One other question: Do you have the usage numbers for **geojson**? Is this sth the geo-community uses a lot?

**Comment by freyfogle** [comment]
geoJSON is used even less than XML. 
I would not support either of those formats until someone specifically asks for them.

**Comment by cohenlea** [comment]
@freyfogle and @moberwasserlechner thanks for the quick replies, I agree, let's leave them out.

**Pull request closed without merging**
