### PR TITLE
Added support for additional properties in the components: region, village

### PR DESCRIPTION
**Pull request by ophiuhus**
Added support for additional properties in the components: region, village

### CODE REVIEW

**Comment by ophiuhus** [comment]
Hey @moberwasserlechner , I'm using your library and urgently require an additional fields in the components. Can you approve my request and release new version? It is failing because there is no api key in the tests.
Thanks

**Comment by moberwasserlechner** [comment]
Hi, adding the fields is of course ok.

But why did you change the whole file instead of only adding the few lines to the java file.

See https://github.com/moberwasserlechner/jopencage#code-style

**Comment by ophiuhus** [comment]
> Hi, adding the fields is of course ok.
> 
> But why did you change the whole file instead of only adding the few lines to the java file.
> 
> See https://github.com/moberwasserlechner/jopencage#code-style

I actually just added few lines. I think the problem is that I'm using Windows and there is different symbol for line break. 
Can you tell me which one you are using?

**Comment by moberwasserlechner** [comment]
It's actually `crlf` although `lf` would be better, but modern IDEs like IDEA does not change the line endings for the whole file. IDEA detects the line ending and leave it be.

Anyway. I gave the OpenCage Docs a quick look and noticed that a few other fields could be added.

I hope it's fine with you that I will add them myself (incl. region and village) and release a version of the lib tomorrow.

It would help if you could share a example location, which which I get response values for "region" and "village".

see https://github.com/moberwasserlechner/jopencage/compare/feature/add_component_fields

BR

**Comment by ophiuhus** [comment]
Funny that I'm using exactly IntellijIDEA. And on PC when I make a diff - I see only 10 lines changed.

If you perform search for "Kovalivka" you will see "village" in 1 item in the response
If you search for "Provance" - there will be "region" in 1 item. Also there are some other fields like "neighbourhood", "unknown", "continent" and maybe some others.

Thanks for your help.

**Comment by moberwasserlechner** [comment]
Do you have line ending changes ignored in IDEA diff view?

ideadiff

I hope you find the setting to disable the change of line endings for future contributions. For this one it is no show stopper ;).

I'll close this PR in favor of #34 and release asap.

**Pull request closed without merging**
